// Playful, slightly dramatic phrases shown when the player tries to leave a match.
const EXIT_PHRASES_ES = [
  'No te vaaaaayas, por favor 🥺',
  '¿En serio te vas a ir? Nos quedaremos tan solos...',
  'Espera, ¡la partida te necesita!',
  'No nos abandones ahora, ¡íbamos ganando!',
  '¡Nooo, quédate un ratito más!',
  'Las cartas se pondrán tristes si te vas.',
  '¿Seguro? Todavía puedes ganar esta partida...',
  'El bot se pondrá triste si te vas ahora.',
  'Piénsalo bien, ¡esto se pone interesante!',
  'No te vayas, ¡falta poco para terminar!',
  '¿De verdad nos dejas así, sin más?',
  'Vuelve, todavía queda diversión por delante.',
  '¡Espera! No te vayas justo ahora.',
  'Nos rompes el corazón si sales ahora mismo.',
  '¿Y si te quedas un poquito más?',
  'La mesa se queda vacía sin ti...',
  'No nos dejes con la partida a medias.',
  'Todavía puedes darle la vuelta a esta partida.',
  '¡Un ratito más, porfa!',
  'Las barajas están tristes solo de pensarlo.',
  '¿Seguro que quieres perderte el final?',
  'No es un adiós, ¡es solo un hasta luego, dinos que sí!',
  'Quédate, prometemos que valdrá la pena.',
  'Justo cuando se ponía bueno...',
  '¡No abandones ahora, campeón!',
  '¿Te vas sin decir ni adiós a las cartas?',
  'El Bot te va a extrañar muchísimo.',
  'Todavía puedes remontar, ¡no te rindas!',
  'Espera un poquito, ¡ya casi termina!',
  'No te vayas, ¡queríamos jugar más contigo!',
  'Nos vas a dejar con la duda de quién ganaba...',
  '¿Seguro seguro? Todavía hay esperanza.',
  'La partida no será la misma sin ti.',
  'Un segundo, ¿de verdad te vas?',
  '¡No nos dejes tirados en la mesa!',
  'Piénsalo dos veces antes de irte...',
  'Esto se pone emocionante, ¡no te lo pierdas!',
  '¿Vas a dejar el juego a medio terminar?',
  'No queremos que te vayas, ¡de verdad!',
  'Solo un poquito más, ¡te lo pedimos!',
  'Las cartas ya te echan de menos.',
  'No es momento de rendirse todavía.',
  '¿Seguro? Podrías arrepentirte luego.',
  'Vamos, quédate un poco más con nosotros.',
  'No te rindas justo ahora...',
  'La partida se queda incompleta sin ti.',
  '¡Todavía puedes ser el ganador!',
  'No nos dejes solos con el Bot.',
  '¿Nos abandonas así, sin despedirte bien?',
  'Espera, esto se pone interesante de verdad.',
  'No te vayas, ¡lo estabas haciendo genial!',
  'Últimamente nadie se queda hasta el final...',
  'Danos una oportunidad más antes de irte.',
  '¿Seguro que no quieres ver cómo termina?',
  'No dejes la partida a la mitad, por favor.',
  'Nos harás muy felices si te quedas un poco más.',
  '¡Todavía no hemos terminado de jugar!',
  'Espera, ¡la victoria puede estar cerca!',
  'No te rindas, ¡esto acaba de empezar!',
  '¿Y si le das una oportunidad más a la partida?',
  'No nos dejes con las cartas en la mano.',
  'Se siente muy solo perder a un jugador así.',
  'Todavía hay tiempo para darle la vuelta.',
  'No te despidas todavía, ¡falta lo mejor!',
  'Un poquito más, ¡te lo prometemos, vale la pena!',
  '¿Seguro que no quieres seguir intentándolo?',
  'La mesa quedará vacía y triste sin ti.',
  'No abandones, ¡todavía puedes sorprendernos!',
  'Espera un momento antes de decidirte.',
  'No te vayas, ¡el Bot también quiere revancha!',
  '¿Ya te rindes? ¡Pero si ibas genial!',
  'Nos dejarás con las ganas de más partidas.',
  'No es un buen momento para irse, ¿no crees?',
  'Todavía puedes cambiar el rumbo de la partida.',
  '¡Quédate, prometemos que no te arrepentirás!',
  '¿Seguro que quieres dejar esto a medias?',
  'No te vayas sin intentarlo una vez más.',
  'La partida aún tiene mucho que ofrecer.',
  'Un ratito más, ¡solo eso pedimos!',
  'No dejes que se apague la partida ahora.',
  '¿De verdad nos dejas con la incógnita?',
  'Todavía puedes disfrutar un poco más.',
  'No te vayas, ¡lo mejor está por venir!',
  'Piensa en las cartas que se quedarán esperando...',
  '¿Seguro que no quieres seguir jugando?',
  'Nos entristece verte partir tan pronto.',
  'No abandones ahora, ¡vamos, tú puedes!',
  'Espera, ¡todavía puedes ganar esta ronda!',
  'No te vayas, ¡esto recién comienza!',
  '¿Y si te quedas solo una rondita más?',
  'Todavía hay margen para el triunfo.',
  'No dejes la partida así, sin cerrar bien.',
  '¡No te rindas, campeón, aún puedes ganar!',
  'Nos quedaremos preguntándonos qué hubiera pasado...',
  '¿Seguro que no quieres intentarlo un poco más?',
  'No te despidas de la partida tan rápido.',
  'Espera, ¡falta muy poco para el final!',
  'No abandones, ¡todavía queda diversión!',
  'Quédate, la partida será mejor contigo.',
];

const EXIT_PHRASES_EN = [
  "Please don't go... 🥺",
  'Are you really leaving? We will be so alone...',
  'Wait, the match needs you!',
  "Don't abandon us now, we were winning!",
  'Nooo, stay a little longer!',
  'The cards will be sad if you leave.',
  'Are you sure? You can still win this match...',
  'The bot will be sad if you leave now.',
  'Think about it, this is getting interesting!',
  "Don't go, we're almost done!",
  'Are you really leaving us like this?',
  "Come back, there's still fun ahead.",
  "Wait! Don't leave just now.",
  "You'll break our hearts if you leave right now.",
  'What if you stay a little bit longer?',
  'The table will be empty without you...',
  "Don't leave us with the match unfinished.",
  'You can still turn this match around.',
  'Just a little longer, please!',
  'The decks are sad just thinking about it.',
  "Are you sure you want to miss the ending?",
  "It's not goodbye, just see you later, say yes!",
  "Stay, we promise it'll be worth it.",
  'Right when it was getting good...',
  "Don't give up now, champion!",
  'Are you leaving without saying goodbye to the cards?',
  'The Bot is going to miss you a lot.',
  "You can still come back, don't give up!",
  "Wait a bit, it's almost over!",
  "Don't leave, we wanted to play more with you!",
  "You'll leave us wondering who was winning...",
  "Sure sure? There's still hope.",
  "The match won't be the same without you.",
  'Wait a second, are you really leaving?',
  "Don't leave us hanging at the table!",
  'Think twice before leaving...',
  "This is getting exciting, don't miss it!",
  'Are you going to leave the game half finished?',
  "We don't want you to leave, really!",
  'Just a little more, we beg you!',
  'The cards already miss you.',
  "It's not time to give up yet.",
  'Are you sure? You might regret it later.',
  'Come on, stay a bit longer with us.',
  "Don't give up right now...",
  'The match stays incomplete without you.',
  'You can still be the winner!',
  "Don't leave us alone with the Bot.",
  'Are you abandoning us without a proper goodbye?',
  'Wait, this is really getting interesting.',
  "Don't go, you were doing great!",
  "Lately nobody stays until the end...",
  'Give us one more chance before you leave.',
  "Are you sure you don't want to see how it ends?",
  "Don't leave the match halfway, please.",
  "You'll make us very happy if you stay a bit longer.",
  "We haven't finished playing yet!",
  'Wait, victory might be close!',
  "Don't give up, this just started!",
  'What if you give the match one more chance?',
  "Don't leave us with the cards in hand.",
  'It feels very lonely to lose a player like you.',
  "There's still time to turn it around.",
  "Don't say goodbye yet, the best part is coming!",
  "Just a bit more, we promise it's worth it!",
  "Are you sure you don't want to keep trying?",
  'The table will remain empty and sad without you.',
  "Don't give up, you can still surprise us!",
  'Wait a moment before deciding.',
  "Don't leave, the Bot wants a rematch too!",
  'Giving up already? But you were doing great!',
  'You will leave us wanting more matches.',
  "It's not a good time to leave, don't you think?",
  "You can still change the course of the match.",
  "Stay, we promise you won't regret it!",
  "Are you sure you want to leave this unfinished?",
  "Don't leave without trying once more.",
  'The match still has a lot to offer.',
  'Just a little longer, that is all we ask!',
  "Don't let the match fade away now.",
  'Are you really leaving us with the uncertainty?',
  'You can still enjoy a bit more.',
  "Don't go, the best is yet to come!",
  'Think of the cards that will be left waiting...',
  "Are you sure you don't want to keep playing?",
  'It saddens us to see you leave so soon.',
  "Don't give up now, come on, you can do it!",
  'Wait, you can still win this round!',
  "Don't go, this is just getting started!",
  'What if you stay for just one more round?',
  "There's still room for triumph.",
  "Don't leave the match like this, unfinished.",
  "Don't give up, champion, you can still win!",
  "We'll be left wondering what could have happened...",
  "Are you sure you don't want to try a bit more?",
  "Don't say goodbye to the match so fast.",
  "Wait, it's almost the end!",
  "Don't give up, there's still fun left!",
  'Stay, the match will be better with you.',
];

export function getRandomExitPhrase(locale: 'en' | 'es'): string {
  const pool = locale === 'es' ? EXIT_PHRASES_ES : EXIT_PHRASES_EN;
  const randomIndex = Math.floor(Math.random() * pool.length);
  return pool[randomIndex] ?? pool[0]!;
}
